on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: "Login to dockerhub"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}

      - name: "Build image"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/taskImage .

      - name: "Push to dockerhub"
        run: docker push ${{secrets.DOCKER_USERNAME}}/taskImage